### ISSUE TITLE
wrong attribute name for live data

### ISSUE THREAD

**Issue by disconn3ct** [freakshock88/hass-populartimes#10]
When live data is available, it adds a `populaTity_is_live` tag in addition to the `populaRity_is_live` tag:

``` yaml
maps_name: Location
address: 123 This Road, This, ST USA
popularity_is_live: false
popularity_sunday:
- 0
- ...
populatity_is_live: true
```

Simple typo in https://github.com/freakshock88/hass-populartimes/blob/720749fd4369118d857e8a59865ae39ccf349033/custom_components/populartimes/sensor.py#L89
